version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: mypassword
      MYSQL_DB: messaging_db
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    container_name: messaging_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MYSQL_DB=messaging_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mypassword
      - MYSQL_HOST=db
      - MYSQL_PORT=3306

volumes:
  db_data:
