name: Docker Build & Push

on:
  push:
    branches: [ "main" ]
    paths:
      - 'messaging_app/**'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ kipt00 }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./messaging_app
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/messaging-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/messaging-app:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
