name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: testdb
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: app
          MYSQL_PASSWORD: app
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      DJANGO_SETTINGS_MODULE: messaging_app.settings
      DB_NAME: testdb
      DB_USER: app
      DB_PASSWORD: app
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      SECRET_KEY: testsecret
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system dependencies (MySQL client headers)
        run: sudo apt-get update && sudo apt-get install -y libmysqlclient-dev

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          pip install -r messaging_app/requirements.txt

      - name: Run Django tests with pytest
        run: |
          cd messaging_app
          mkdir -p reports
          pytest --junitxml=reports/junit.xml

      - name: Upload test report (JUnit XML)
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: messaging_app/reports/junit.xml
